### ISSUE TITLE
rio_de_hola - cannot zoom in with mouse wheel

### ISSUE THREAD

**Issue by prock-fife** [fifengine/fifengine-demos#10]
For some reason I cannot zoom in with the mouse wheel but I can zoom out.  I investigated this quickly and determined that the mouse wheel moved up event isn't been triggered.

**Comment by prock-fife** [comment]
Seems that widgets handle the mouse wheel up event no issues.  Could it be fifechan is eating the event somehow?

**Comment by Niektory** [comment]
OK, this is bizarre. I've tried a bunch of things and determined that this bug triggers when a widget is placed at coordinates (0,0). In this case it's `rootpanel`. If it's moved somewhere else the wheel works correctly.

**Comment by prock-fife** [comment]
nice catch...   I cant see anything in FIFE that would prevent that event from being sent to the gui managers.    Must be a fifechan bug or perhaps something in pychan.

**Comment by helios2000** [comment]
Fixed with https://github.com/fifengine/fifengine/commit/dad07deb991fa366480948bf64545ef81fafbbf4
